### ISSUE TITLE
https user/password not work

### ISSUE THREAD

**Issue by easychen** [seedboxes/pibox#7]
while ftp account works well , https account not work . the window pop up again and again.

**Comment by KiPiCoOl** [comment]
You password exceeds 8 characters ?
If yes, It's normal.

**Comment by gpapin** [comment]
Same issue here

**Comment by gpapin** [comment]
The installation process is a bit confusing,
I had a look at the logs and everything seems fine, When I then check the status using the supervisor the php and web are stopped ...

Here are some logs if needed:

```
~/pibox_install$ pibox logs

 *** LOGS ***

 Startup logs for container named pibox

                         __     __   __
                        |__) | |__) /  \ \_/
                        |    | |__) \__/ / \


 ==> RUTORRENT setup

 ==> CREDENTIALS
   > A password file already exists... [SKIPPING]
   > Setting up username/password for FTP access... [SUCCESS]

 ==> SSL
   > A certificate file already exists... [SKIPPING]

 ==> SERVICES
   > Starting php... [SUCCESS]
   > Starting http server... [SUCCESS]

 ==> PIBOX STARTED SUCCESSFULLY
2016-05-09 13:35:04,149 CRIT Set uid to user 0
2016-05-09 13:35:04,173 CRIT Server 'unix_http_server' running without any HTTP authentication checking

~/pibox_install$ pibox status

 *** STATUS ***

 Services status for container named pibox

ftp                              RUNNING    pid 52, uptime 0:20:24
php                              STOPPED    Not started
torrent                          RUNNING    pid 53, uptime 0:20:24
web                              STOPPED    Not started
```

**Comment by gpapin** [comment]
It turns out that the password was already defined by one of my previous test.
So if you see this :
`A password file already exists... [SKIPPING]`

Then remove the docker image `pibox rm` then remove your local folder for pibox `rm -rf ~/pibox` and finaly relaunch your pibox `pibox run` (make sure you have your username and password defined in the conf file)

This solved the issue for me
